[application]
name = "share meal"

[bundle]
identifier = "com.phuditc.sharemeal"
displayname = "Share Meal"
name = "Share Meal"
publisher = "Phudit Chuengjaroen"
icon = [
    "icons/16x16.png",
    "icons/32x32.png",
    "icons/64x64.png",
    "icons/256x256.png",
    "assets/favicon.ico"
]
category = "Utility"
copyright = "Phudit Chuengjaroen"
short_description = "Split bills fairly by item, not just total. Track who ordered what and pay your share only"

[web.app]
# HTML title tag content
title = "Shared Meal"
# base_path = "share-meal-web"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
