[application]
name = "share meal"

[bundle]
identifier = "com.phuditc.sharemeal"
publisher = "Phudit Chuengjaroen"
icon = ["assets/app-icon-share-meal.png"]
category = "Utilities"
copyright = "Phudit Chuengjaroen"
short_description = "Split bills fairly by item, not just total. Track who ordered what and pay your share only"


[web.app]
# HTML title tag content
title = "shared_meal"
# base_path = "share-meal-web"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
